name: TobaccoPipes
description: Tobacco pipes you can smoke with
author: Chai
main: com.chai.tobaccoPipes.Main
version: 1.0
api-version: 1.15

commands:
  pipes:
    description: Tobacco pipes
    default: true
    usage: "Usage: /pipes [info|reload]"

permissions:
  pipes.reload:
    default: op
    description: Allows you to reload the config